name: Build with uv
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v1
        with:
          version: 0.4.5
          enable-cache: true
      - name: Build with uv
        run: uv build
