name: Lint
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v1
        with:
          version: 0.4.5
          enable-cache: true
      - name: Install the project
        run: uv sync -p ${{ matrix.python-version }} --all-extras --dev
      - name: Run the lint
        run: uv run ruff check .
      - name: Run the format
        run: uv run ruff format .
