name: Run the test suite
on: push

jobs:
  test:
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v1
        with:
          version: 0.4.5
          enable-cache: true
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Install the project
        run: uv sync -p ${{ matrix.python-version }} --all-extras --dev
      - name: Test
        run: uv run pytest --cov=. tests/
      - name: Minimize uv cache
        run: uv cache prune --ci
