name: Run the test suite
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v1
        with:
          version: 0.4.5
          enable-cache: true
      - name: Test
        run: uv run --frozen pytest --cov=. tests/
